In [1]:
import numpy as np
import pandas as pd
list=[[1,'Smith',50000],[2,'Jones',60000]]

df=pd.DataFrame(list)
df

   0      1      2
0  1  Smith  50000
1  2  Jones  60000

In [2]:
df.columns=['Empd','Name','Salary']
df

   Empd   Name  Salary
0     1  Smith   50000
1     2  Jones   60000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Empd    2 non-null      int64
 1   Name    2 non-null      object
 2   Salary  2 non-null      int64
dtypes: int64(2), object(1)
memory usage: 180.0+ bytes

In [5]:
df=pd.read_csv("/content/50stocks.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rank                 50 non-null     int64
 1   Symbol               50 non-null     object
 2   Company Name         50 non-null     object
 3   Sector               50 non-null     object
 4   Market Cap (INR Cr)  50 non-null     int64
 5   Exchange             50 non-null     object
dtypes: int64(2), object(4)
memory usage: 2.5+ KB

In [6]:
df.head()

,Rank,Symbol,Company Name,Sector,Market Cap (INR Cr),Exchange
0,1,RELIANCE,Reliance Industries Ltd.,"Oil, Gas & Consumable Fuels",1580194,NSE/BSE
1,2,HDFCBANK,HDFC Bank Ltd.,Financial Services (Banking),1111989,NSE/BSE
2,3,BHARTIARTL,Bharti Airtel Ltd.,Telecommunication,1086727,NSE/BSE
3,4,ICICIBANK,ICICI Bank Ltd.,Financial Services (Banking),940846,NSE/BSE
4,5,SBIN,State Bank of India,Financial Services (Banking),880693,NSE/BSE

In [7]:
df.tail()

,Rank,Symbol,Company Name,Sector,Market Cap (INR Cr),Exchange
45,46,DRREDDY,Dr. Reddy's Laboratories Ltd.,Healthcare & Pharmaceuticals,100679,NSE/BSE
46,47,TATACONSUM,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,94713,NSE/BSE
47,48,MAXHEALTH,Max Healthcare Institute Ltd.,Healthcare / Services,91583,NSE/BSE
48,49,BPCL,Bharat Petroleum Corporation Ltd.,"Oil, Gas & Consumable Fuels",88500,NSE/BSE
49,50,HEROMOTOCO,Hero MotoCorp Ltd.,Automobile & Auto Components,85200,NSE/BSE

In [12]:
df.describe()

           Rank  Market Cap (INR Cr)
count  50.00000         5.000000e+01
mean   25.50000         3.568411e+05
std    14.57738         3.015745e+05
min     1.00000         8.520000e+04
25%    13.25000         1.770518e+05
50%    25.50000         2.786600e+05
75%    37.75000         4.007682e+05
max    50.00000         1.580194e+06